apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: axion-secret
spec:
  provider: azure
  parameters:
    clientId: "6108e316-c14f-4d72-8792-81711ab1ed9c"
    tenantId: "98cc0d54-26f0-4577-8430-8890910ec6a1"
    keyvaultName: Axion-keyvault
    objects: |
      array:
        - |
          objectName: Axion-Username
          objectType: secret
        - |
          objectName: Axion-Password
          objectType: secret
  secretObjects:
    - secretName: pgadmin-secret
      type: Opaque
      data:
        - objectName: Axion-Username
          key: Axion-Username
        - objectName: Axion-Password
          key: Axion-Password
